remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
show_donwloads: true 
markdown: kramdown
highlighter: rouge
input: GFM

kramdown:
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: table
    bold_every: 5
